export const Colors = {
	light: {
		primary: '#8B5CF6',
		primaryLight: '#DDD6FE',
		primaryText: '#4C1D95',
		secondaryText: '#4B5563',
		secondary: '#FDBA74',
		secondaryLight: '#FFEDD5',
		background: '#EFEEFF',
		error: '#F87171',
		disabled: '#D1D5DB',
		white: '#FFFFFF',
	},
	dark: {
		primary: '#8B5CF6',
		primaryLight: '#DDD6FE',
		primaryText: '#4C1D95',
		secondaryText: '#4B5563',
		secondary: '#FDBA74',
		secondaryLight: '#FFEDD5',
		background: '#EFEEFF',
		error: '#F87171',
		disabled: '#D1D5DB',
		white: '#FFFFFF',
	},
};
